apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: temperature-proxy

resources:
  - namespace.yaml
  - configmap.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - ingress.yaml
  - pdb.yaml
  - networkpolicy.yaml

commonLabels:
  app.kubernetes.io/name: temperature-proxy
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/managed-by: kustomize
