apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: temperature-proxy-pdb
  namespace: temperature-proxy
  labels:
    app.kubernetes.io/name: temperature-proxy
    app.kubernetes.io/component: pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: temperature-proxy
