apiVersion: v1
kind: Service
metadata:
  name: temperature-proxy
  namespace: temperature-proxy
  labels:
    app.kubernetes.io/name: temperature-proxy
    app.kubernetes.io/component: service
spec:
  type: ClusterIP
  selector:
    app: temperature-proxy
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
