apiVersion: v1
kind: ServiceAccount
metadata:
  name: temperature-proxy-sa
  namespace: temperature-proxy
  labels:
    app.kubernetes.io/name: temperature-proxy
    app.kubernetes.io/component: serviceaccount
automountServiceAccountToken: false
